name: App CI (test)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt update -yq && sudo apt install build-essential docker docker-compose -yq
    - name: Setup environment
      run: cp .env.example .env && systemctl start docker
    - name: Verification
      run: sudo make check
    - name: Start app
      run: sudo make start
    - name: Stop app
      run: sudo make stop
