name: App CI (test)

on:
  push:
    branches: [ main, create-test-ci ]
  pull_request:
    branches: [ main, create-test-ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt update -yq && sudo apt install build-essential
      
    - name: Checkout last version
      uses: actions/checkout@v3
      
    - name: Setup environment
      run: cp .env.example .env
      
    - name: Run docker-compose
      uses: isbang/compose-action@v1.0.0
      
    - name: Verification
      run: sudo docker-compose exec -T pc-web-front npm run build && sudo docker-compose exec -T pc-web-front npm run check
